name: GitHub Actions Test
on: [push]
jobs:
  Test-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js '16'
      uses: actions/setup-node@v3
      with:
        node-version: '16'
      - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
      - name: Install dependencies
        run: npm ci
      - run: npm test